on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v2
      - name: List of foles
        run: ls -la /home/runner/work/go-threadsnake/go-threadsnake
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.17.6.linux-amd64.tar.gz"
          project_path: "/home/runner/work/go-threadsnake/go-threadsnake"
          binary_name: "go-threadsnake"
          ldflags: "-X main.version=${{ github.event.release.name }}"
          extra_files: LICENSE README.md